### ISSUE TITLE
README.md Does not reflect correct links

### ISSUE THREAD

**Issue by ohitstom** [spicetify/.github#1]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: n/a
- Spicetify version:n/a
```

### 📝 Description

The links to the spicetify.app docs page are incorrect and are dead links

### 📸 Screenshots

![lol](https://user-images.githubusercontent.com/22730962/163688674-9adf20fc-0e35-440b-91f3-0f8db28680ca.gif)

**Comment by afonsojramos** [comment]
Closed in #2.
