### ISSUE TITLE
Move the extensions and custom apps from the repo

### ISSUE THREAD

**Issue by CharlieS1103** [spicetify/.github#5]
### 📝 Provide a description of the new feature

We could move all the extensions and custom apps that are in this repo to the existing repos on the org. This move would make quite a bit of sense in my opinion and might sizably reduce the base size of the install

**Comment by afonsojramos** [comment]
@CharlieS1103 are you sure you opened this in the right repo?

**Comment by CharlieS1103** [comment]
@afonsojramos nope
